#ifndef __ERROR_CODE_HPP__
#define __ERROR_CODE_HPP__

#include <string>
class ErrorCode
{
public:
    enum class Code
    {
        // BRI
        BRI_A1_READ_MEMORY_ERROR,
        BRI_A2_TAP_BELOW_ONE_MINUTE,
        BRI_A3_INSUFFICIENT_BALANCE,
        BRI_A4_TAP_CODE_NOT_FOUND,
        BRI_A5_TAP_CHECK_EXCEPTION,
        BRI_A6_WRITE_MEMORY_ERROR,
        BRI_A7_WRITE_BLOCK_EXCEPTION,
        BRI_A8_POWER_SLOT_SAM_ERROR,
        BRI_A9_OPEN_SLOT_SAM_ERROR,
        BRI_AA_BALANCE_CHECK_EXCEPTION,

        // BNI
        BNI_B1_POWER_SLOT_SAM_ERROR,
        BNI_B2_OPEN_SLOT_SAM_ERROR,
        BNI_B3_INSUFFICIENT_BALANCE,
        BNI_B4_TAP_CODE_NOT_FOUND,
        BNI_B5_READ_MEMORY_ERROR,
        BNI_B6_TAP_CHECK_EXCEPTION,
        BNI_B7_WRITE_MEMORY_ERROR,
        BNI_B8_WRITE_BLOCK_EXCEPTION,
        BNI_B9_TAP_BELOW_ONE_MINUTE,
        BNI_BA_BALANCE_CHECK_EXCEPTION,

        // DKI
        DKI_C1_POWER_SLOT_SAM_ERROR,
        DKI_C2_OPEN_SLOT_SAM_ERROR,
        DKI_C3_BALANCE_CHECK_EXCEPTION,
        DKI_C4_READ_MEMORY_ERROR,
        DKI_C5_KLG_EXPIRED,
        DKI_C6_INSUFFICIENT_BALANCE,
        DKI_C7_TAP_CODE_NOT_FOUND,
        DKI_C8_TAP_CHECK_EXCEPTION,
        DKI_C9_TAP_BELOW_ONE_MINUTE,
        DKI_CA_WRITE_MEMORY_ERROR,
        DKI_CB_WRITE_BLOCK_EXCEPTION,

        // MANDIRI
        MANDIRI_D1_POWER_SLOT_SAM_ERROR,
        MANDIRI_D2_OPEN_SLOT_SAM_ERROR,
        MANDIRI_D3_BALANCE_CHECK_EXCEPTION,
        MANDIRI_D4_TAP_BELOW_ONE_MINUTE,
        MANDIRI_D5_INSUFFICIENT_BALANCE,
        MANDIRI_D6_TAP_CODE_NOT_FOUND,
        MANDIRI_D7_TAP_CHECK_EXCEPTION,
        MANDIRI_D8_WRITE_MEMORY_ERROR,
        MANDIRI_D9_WRITE_BLOCK_EXCEPTION,
        MANDIRI_DA_READ_MEMORY_ERROR,

        // BCA
        BCA_E1_INIT_SAM_ERROR,
        BCA_E2_POWER_SLOT_SAM_ERROR,
        BCA_E3_BALANCE_CHECK_EXCEPTION,
        BCA_E4_TAP_BELOW_ONE_MINUTE,
        BCA_E5_INSUFFICIENT_BALANCE,
        BCA_E6_TAP_CODE_NOT_FOUND,
        BCA_E7_TAP_CHECK_EXCEPTION,
        BCA_E8_WRITE_MEMORY_ERROR,
        BCA_E9_WRITE_BLOCK_EXCEPTION,
        BCA_EA_OPEN_SLOT_SAM_ERROR,
        BCA_EB_READ_MEMORY_ERROR,

        // GENERAL
        GENERAL_F1_UNKNOWN_CARD,
        GENERAL_F2_BALANCE_CHECK_EXCEPTION,
        GENERAL_F3_CARD_NOT_DETECTED,
        GENERAL_F4_NFC_EXCEPTION,
        GENERAL_F5_DEVICE_NOT_REGISTERED,
        GENERAL_F6_DEBIT_DEVICE_LOST_CONTACT
    };

    static std::string toString(const Code &errorCode);
};

#endif